---
apiVersion: v1
kind: Secret
metadata:
  name: simple-amqp
type: Opaque
stringData:
  connect.json: |-
    {
        "scheme": "amqp",
        "host": "simple-router"
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recv-amqp
spec:
  replicas: 1
  selector:
    matchLabels:
      application: recv-amqp
  template:
    metadata:
      labels:
        application: recv-amqp
    spec:
      containers:
      - image: quay.io/gordons/recv
        imagePullPolicy: IfNotPresent
        name: recv
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: simple-amqp
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: send-amqp
spec:
  replicas: 1
  selector:
    matchLabels:
      application: send-amqp
  template:
    metadata:
      labels:
        application: send-amqp
    spec:
      containers:
      - image: quay.io/gordons/send
        imagePullPolicy: IfNotPresent
        name: send
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: simple-amqp
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: simple-dummy-cert
spec:
  commonName: dummy
  issuerRef:
    name: simple-router-ca
  secretName: simple-dummy-cert
---
apiVersion: v1
kind: Secret
metadata:
  name: simple-amqps
type: Opaque
stringData:
  connect.json: |-
    {
        "scheme": "amqps",
        "host": "simple-router.myproject.svc.cluster.local",
        "tls": {
            "ca": "/etc/messaging/certs/ca.crt",
            "verify": true
        }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recv-amqps
spec:
  replicas: 1
  selector:
    matchLabels:
      application: recv-amqps
  template:
    metadata:
      labels:
        application: recv-amqps
    spec:
      containers:
      - image: quay.io/gordons/recv
        imagePullPolicy: IfNotPresent
        name: recv
        env:
        - name: ADDRESS
          value: foo
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
        - name: ca-cert
          mountPath: "/etc/messaging/certs/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: simple-amqps
      - name: ca-cert
        secret:
          secretName: simple-dummy-cert
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: send-amqps
spec:
  replicas: 1
  selector:
    matchLabels:
      application: send-amqps
  template:
    metadata:
      labels:
        application: send-amqps
    spec:
      containers:
      - image: quay.io/gordons/send
        imagePullPolicy: IfNotPresent
        name: send
        env:
        - name: ADDRESS
          value: foo
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
        - name: ca-cert
          mountPath: "/etc/messaging/certs/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: simple-amqps
      - name: ca-cert
        secret:
          secretName: simple-dummy-cert
---