apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: cluster2-ca-issuer
spec:
  ca:
    secretName: inter-router-ca
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cluster2-inter-router-tls
spec:
  commonName: cluster2-inter-router-default.apps.cluster2.devcluster.openshift.com
  issuerRef:
    name: cluster2-ca-issuer
  secretName: cluster2-inter-router-tls
---
apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: cluster2
spec:
  sslProfiles:
  - name: inter-router-tls
    caCert: cluster2-inter-router-tls
    credentials: cluster2-inter-router-tls
  interRouterConnectors:
  - host: cluster1-inter-router-default.apps.grs-cluster1.devcluster.openshift.com
    port: 443
    verifyHostname: false # due to https://github.com/interconnectedcloud/qdr-operator/issues/16
    sslProfile: inter-router-tls
