---
apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: cluster1
spec:
  sslProfiles:
  - name: inter-router-tls
    mutualAuth: true
  interRouterListeners:
  - name: inter-router
    port: 55672
    expose: true
    authenticatePeer: true
    saslMechanisms: EXTERNAL
    sslProfile: inter-router-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cluster2-inter-router-tls
spec:
  commonName: cluster2-inter-router-default.apps.grs-cluster2.devcluster.openshift.com
  issuerRef:
    name: cluster1-inter-router-tls-ca
  secretName: cluster2-inter-router-tls
---
