apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: custom-ports
spec:
  listeners:
  - name: amqp
    port: 6666
  - name: amqps
    port: 7777
    sslProfile: default
  - name: console
    port: 8888
    http: true
  interRouterListeners:
  - name: inter-router
    port: 5555
    sslProfile: default
