---
apiVersion: v1
kind: Secret
metadata:
  name: multicast-example
type: Opaque
stringData:
  connect.json: |-
    {
        "scheme": "amqp",
        "host": "multicast-example"
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recv-foo
spec:
  replicas: 2
  selector:
    matchLabels:
      application: recv-foo
  template:
    metadata:
      labels:
        application: recv-foo
    spec:
      containers:
      - image: quay.io/gordons/recv
        imagePullPolicy: IfNotPresent
        name: recv
        env:
        - name: ADDRESS
          value: "foo"
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: multicast-example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: send-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      application: send-foo
  template:
    metadata:
      labels:
        application: send-foo
    spec:
      containers:
      - image: quay.io/gordons/send
        imagePullPolicy: IfNotPresent
        name: send
        env:
        - name: ADDRESS
          value: "foo"
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: multicast-example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recv-bar
spec:
  replicas: 2
  selector:
    matchLabels:
      application: recv-bar
  template:
    metadata:
      labels:
        application: recv-bar
    spec:
      containers:
      - image: quay.io/gordons/recv
        imagePullPolicy: IfNotPresent
        name: recv
        env:
        - name: ADDRESS
          value: "xyz/bar"
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: multicast-example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: send-bar
spec:
  replicas: 1
  selector:
    matchLabels:
      application: send-bar
  template:
    metadata:
      labels:
        application: send-bar
    spec:
      containers:
      - image: quay.io/gordons/send
        imagePullPolicy: IfNotPresent
        name: send
        env:
        - name: ADDRESS
          value: "xyz/bar"
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: multicast-example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recv-baz
spec:
  replicas: 2
  selector:
    matchLabels:
      application: recv-baz
  template:
    metadata:
      labels:
        application: recv-baz
    spec:
      containers:
      - image: quay.io/gordons/recv
        imagePullPolicy: IfNotPresent
        name: recv
        env:
        - name: ADDRESS
          value: "baz"
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: multicast-example
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: send-baz
spec:
  replicas: 1
  selector:
    matchLabels:
      application: send-baz
  template:
    metadata:
      labels:
        application: send-baz
    spec:
      containers:
      - image: quay.io/gordons/send
        imagePullPolicy: IfNotPresent
        name: send
        env:
        - name: ADDRESS
          value: "baz"
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: multicast-example
---
