apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Interconnect
metadata:
  name: authenticated
spec:
  listeners:
  - name: amqp
    port: 5672
    host: 127.0.0.1
  - name: amqps
    port: 5671
    sslProfile: default
    authenticatePeer: true
    saslMechanisms: EXTERNAL
    expose: true
  - name: http
    port: 8080
    http: true
  sslProfiles:
  - name: default
    mutualAuth: true
